### ISSUE TITLE
Create a Wiki for speakeasy

### ISSUE THREAD

**Issue by railsstudent** [speakeasyjs/speakeasy#73]
I don't know how to make PR for wiki.
Please go to https://github.com/railsstudent/speakeasy/wiki and have a look.

If you like it, please merge the wiki back to the repo. 

Thanks,

Connie

**Comment by mikepb** [comment]
Great job on the wiki!



Since you have administrative rights for the main Speakeasy repo, you can merge the wiki yourself via git as well. The URL for the Speakeasy repo is:

https://github.com/speakeasyjs/speakeasy.wiki.git <https://github.com/speakeasyjs/speakeasy.wiki.git>

or via SSH:

git@github.com:speakeasyjs/speakeasy.wiki.git

You can check out your wiki using either of:

git clone https://github.com/railsstudent/speakeasy.wiki.git <https://github.com/railsstudent/speakeasy.wiki.git>
git clone git@github.com:railsstudent/speakeasy.wiki.git

Then add the main repository:

git remote add upstream https://github.com/speakeasyjs/speakeasy.wiki.git <https://github.com/speakeasyjs/speakeasy.wiki.git>
git remote add upstream git@github.com:speakeasyjs/speakeasy.wiki.git

Then push your changes:

git push upstream master

These instructions are for using command line git. If you are using the GitHub app, adjust accordingly.

For more information:

https://help.github.com/articles/about-github-wikis/ <https://help.github.com/articles/about-github-wikis/>
https://help.github.com/articles/adding-and-editing-wiki-pages-locally/ <https://help.github.com/articles/adding-and-editing-wiki-pages-locally/>

https://help.github.com/articles/connecting-to-github-with-ssh/ <https://help.github.com/articles/connecting-to-github-with-ssh/>
https://help.github.com/articles/pushing-to-a-remote/ <https://help.github.com/articles/pushing-to-a-remote/>

**Comment by railsstudent** [comment]
Done.

**Comment by markbao** [comment]
@railsstudent Thanks for this, looks great.
